### ISSUE TITLE
Support distributed processing

### ISSUE THREAD

**Issue by nihey** [nihey/StarWarsIntroRecorder#1]
Just 3 days after we've got started with the processing queue have over **200 video requests** that will take more than 8 days to be processed on current scenario.

I thought about a **round-robin hub architecture**, basically a `hub` (or `load ballancer`) distributes the requests through multiple instances of `StarWarsIntroRecorder`.

![screenshot from 2016-02-10 19 39 14](https://cloud.githubusercontent.com/assets/5278570/12962899/ce6f612a-d02e-11e5-9ce0-6dfff5c7c10f.png)

Processed videos could be then transfered to the `hub` where they'll be finally served to the end-user.

Some important questions will have to be answered through this process:

- How are we going to know which videos are in which queue? (So that we don't have the same video being rendered on different servers).
- How are we going to make sure donators have the least queue time they can get?

**Comment by BrOrlandi** [comment]
The implementation is done. Need more tests to check if everything is ok.

**Comment by nihey** [comment]
As @BrOrlandi said, the base for this is done, other bugs/enhancements can be reported as other issues.

We'll see how much parallel processors we'll need to get this queue to reduce.
